# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
      - image: circleci/mysql:latest-ram
        environment:
          MYSQL_HOST: 127.0.0.1
          MYSQL_DB: circle_test
          MYSQL_USER: ubuntu
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_PASSWORD:
     
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo/

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "lumberjack_spring/pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: cd lumberjack_spring && mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "lumberjack_spring/pom.xml" }}

      # run tests!
      - run: mkdir lumberjack_spring/config/
          && mv circleci_config/* lumberjack_spring/config/ 
          && cd lumberjack_spring/ 
          && mvn package

      - store_test_results:
          path: lumberjack_spring/target/surefire-reports
      
      - store_artifacts:
          path: lumberjack_spring/target/*.jar

